name: Chaining Jobs

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      run-job-3:
        description: "Run job 3"
        required: true
        type: boolean
jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Output for Job 1
        run: echo "Hello from Job 1. Run Job 3 equals ${{ github.event.inputs.run-job-3 }}"